### PR TITLE
Merged upstream

### PR DESCRIPTION
**Pull request by lhstrh**

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you very much! This is a really interesting proposal. 

Scanned through the code, as far as I see it would create sub-changelogs for the sub modules, and not merge the changes into the parent changelog. Please correct me if I miss-read the code.

I am curious in how this approach would differ than calling the action a second time for the other repository (in a new step) and then afterwards merge the resulting changelogs?

**Comment by lhstrh** [comment]
I'm using my fork to compile release notes for [Lingua Franca](https://github.com/lf-lang/lingua-franca/), which has several submodules that live separate lives because they use different build systems and are concerned with different aspects of the project (i.e., runtime support), but their code it tightly coupled with the compiler, so we release everything together. You can see the result [here](https://github.com/lf-lang/lingua-franca/releases/tag/v0.4.0).

Indeed, the release notes of the submodules are essentially appended to the main release notes, which could also be achieved by doing multiple runs of the action and merging the results, but the user would then have to figure out the relevant start and end refs on their own, which can be a bit tricky. I've also added the option to conveniently add some introductory text that is inserted after the header.

I haven't been able to successfully merge what I have in [my develop branch](https://github.com/lhstrh/release-changelog-builder-action) with yours, and my current implementation isn't able to handle the fact that we've changed the paths of the sub modules :man_facepalming:, so I'm probably going to go with a more manual approach for our upcoming release, anyway.

But do you think it would be worth trying to incorporate a feature like this? If so, perhaps we can join forces...

**Comment by mikepenz** [comment]
Thank you for taking the time to go into much details on your usecase. 

> but the user would then have to figure out the relevant start and end refs on their own
I believe this is one of the major arguments or items to solve, to make it convenient for the integration. Based on that I do understand now why you went that path.

Overall offering a solution to handle sub-modules sounds like a very helpful addition. 
I need to give the code another look and think through it more. 

Really appreciate it!

**Comment by lhstrh** [comment]
Here you can see the generated release notes for our project, which has multiple submodules:
https://github.com/lf-lang/lingua-franca/pull/1963/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

My fork can now also deal with submodules that have moved location in the source tree...

**Pull request closed without merging**
