### PR TITLE
Configuration that uses a different metadata hash when comparing commits. Useful when you are using subtree in your project

### PR DESCRIPTION
**Pull request by leonardo-lopes-playkids**

### CODE REVIEW

**Comment by mikepenz** [comment]
@leonardo-lopes-playkids could you also please add some testcases to verify this new feature?

could you please give a bit more context on this functionality in the PR description?

**Comment by leonardo-lopes-playkids** [comment]
> @leonardo-lopes-playkids could you also please add some testcases to verify this new feature?
> 
> could you please give a bit more context on this functionality in the PR description?
> 
> Thank you so much for the PR

Sure. I will will write the testcases and a better description. But just so you know, the current testcases from 'develop' already fail when I do "npm run all"
Test Suites: 2 failed, 2 passed, 4 total
Tests:       10 failed, 9 passed, 19 total

**Comment by mikepenz** [comment]
@leonardo-lopes-playkids tests pass on GitHub Actions: https://github.com/mikepenz/release-changelog-builder-action/runs/2054398786?check_suite_focus=true#step:4:505


I was also wondering if the action isn't already capable of generating logs for submodules (as those are basically other repos) as the action allows you to configure the repo, and from and to tag.

**Comment by leonardo-lopes-playkids** [comment]
Ok, I will have to review the tests and see why they are failing. 
In our project, we have a subtree branch upm that is unable to get the changelog information because when our CI uses the git subtree command to split the files to a subtree branch, git changes the values of these hashes and the action will not work, that's why we had to create a new hash that is calculated using information from author+date+message. That way we make sure the hashes will always be the same

**Pull request closed without merging**
