### PR TITLE
Add note for initial releases

### PR DESCRIPTION
**Pull request by ccremer**

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you for this PR. 

Wonder how it may can be combined with the notes highlighted in the `Configuration` section: https://github.com/mikepenz/release-changelog-builder-action#configuration

Screenshot 2021-11-04 at 11 51 45


In the rarest cases there would be no checkout, as it would be also required to retrieve the `configuration.json`

**Comment by ccremer** [comment]
@mikepenz please have another look

**Comment by mikepenz** [comment]
I'd actually propose to make option `2` the preferred one, as it is anyways suggested to checkout so the action has access to the configuration.json :)

**Comment by ccremer** [comment]
I'm not quite sure what you mean. I didn't mean to provide preferences for either option, I was just listing that I see 2 different approaches. Did you mean to omit the option to use a tag like `v0.0.1` ?

**Pull request merged**
