### PR TITLE
Adding baseUrl for GHE auth

### PR DESCRIPTION
**Pull request by leog**
Hello there!

I wanted to use this great GH Action within my company’s GitHub Enterprise instance and to do that I detected that there is a missing configuration that could make octokit work with it, so here is the contribution.

Thanks!

### CODE REVIEW

**Comment by mikepenz** [comment]
Thank you so much. That's a great contribution. Will review it as soon as possible

**Comment by mikepenz** [comment]
Thank you very much for the contribution. 

Reverted to keep the `package-lock.json` and removed the `ci` adjustment as this would have practically pinged your server with this repos secret which is a serious security problem.

**Comment by leoglobant** [comment]
Thank you for taking my contribution. 

Understood about the `package-lock.json` and the `ci` changes were not the real GHE server, just an example corp server 🙂

**Comment by leog** [comment]
Thank you for taking my contribution. 

Understood about the `package-lock.json` and the `ci` server I added was not a real GHE server, just an example 😉

**Pull request merged**
